language: php

dist: trusty

addons:
  hosts:
    - gssp.stepup.example.com
  apt:
    packages:
      - cmake
      - apache2

php:
  - 5.6
  - 7.0
  - 7.1

cache:
  directories:
    - ~/.composer/cache/files

before_script:
  # configure ssl
  - sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/certs/gssp.key -out /etc/ssl/certs/gssp.crt -subj "/C=NL/ST=Netherlands/L=Amsterdam/O=TEST/CN=gssp.stepup.example.com"

  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  - export PHP_VERSION=$(phpenv version-name)
  - sudo cp ~/.phpenv/versions/${PHP_VERSION}/etc/php-fpm.conf.default ~/.phpenv/versions/${PHP_VERSION}/etc/php-fpm.conf
  - sudo cp ~/.phpenv/versions/${PHP_VERSION}/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/${PHP_VERSION}/etc/php-fpm.d/www.conf || true
  - sudo a2enmod rewrite actions fastcgi alias ssl proxy proxy_fcgi
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/${PHP_VERSION}/etc/php.ini
  - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
  - sudo chown -R travis:travis /var/lib/apache2/fastcgi
  - ~/.phpenv/versions/${PHP_VERSION}/sbin/php-fpm

  # configure apache virtual hosts
  - sudo cp -f ${TRAVIS_BUILD_DIR}/travis-ci-apache.conf /etc/apache2/sites-available/000-default.conf
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
  - sudo sed -e "s?%PHP_VERSION%?${PHP_VERSION}?g" --in-place /etc/apache2/sites-available/000-default.conf
  - sudo cat /etc/apache2/sites-available/000-default.conf

  # Create apache error log.
  - touch $TRAVIS_BUILD_DIR/error.log
  - sudo service apache2 restart

  # Install dependencies
  - composer install

  # Check if everything runs properly
  - ps aux | grep php-fpm
  - netstat -an | grep :9000
  - curl --insecure https://gssp.stepup.example.com
  - curl --insecure https://gssp.stepup.example.com/bootstrap.min.js

script:
  # Test if the website is actually running
  - ./bin/bootstrap_phantomjs.sh
  - composer test

after_script:
  - cat $TRAVIS_BUILD_DIR/error.log
  - cat $TRAVIS_BUILD_DIR/build/*.html
  - sudo cat /var/log/syslog
